### ISSUE TITLE
Cannot format golang file in sublime text

### ISSUE THREAD

**Issue by 7flash** [golang/sublime-config#11]
```
Traceback (most recent call last):
File "/Users/gur/Library/Application Support/Sublime Text/Installed Packages/Gofmt.sublime-package/gofmt.py", line 257, in run_formatter
formatter = Formatter(view)
File "/Users/gur/Library/Application Support/Sublime Text/Installed Packages/Gofmt.sublime-package/gofmt.py", line 166, in __init__
self.cmds = [Command(cmd, self.view, self.window) for cmd in cmds]
File "/Users/gur/Library/Application Support/Sublime Text/Installed Packages/Gofmt.sublime-package/gofmt.py", line 166, in <listcomp>
self.cmds = [Command(cmd, self.view, self.window) for cmd in cmds]
File "/Users/gur/Library/Application Support/Sublime Text/Installed Packages/Gofmt.sublime-package/gofmt.py", line 77, in __init__
self.window)
File "/Users/gur/Library/Application Support/Sublime Text/Lib/python33/golangconfig.py", line 227, in subprocess_info
raise exception
golangconfig.EnvVarError: The following environment variable is currently unset: GOPATH
```

I have added in my ~/.zshrc

```
export GOPATH=/usr/local/go
export PATH=$PATH:$GOPATH/bin
```

And added in Golang.sublime-settings

```
{
    "root": "/usr/local/go/bin"
}
```

**Comment by naveenpopclub** [comment]
I am also facing same issue
